# Generated by Django 4.0.5 on 2022-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0006_produkty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
